# Generated by Django 5.1.15 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("soils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Informativa"),
                            ("warning", "Advertencia"),
                            ("danger", "Crítica"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="nivel",
                    ),
                ),
                ("message", models.TextField(verbose_name="mensaje")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada el"),
                ),
                (
                    "acknowledged",
                    models.BooleanField(default=False, verbose_name="reconocida"),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="soils.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
