# Generated by Django 5.1.15 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        ("soils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horizon_days",
                    models.PositiveIntegerField(
                        default=180, verbose_name="horizonte (días)"
                    ),
                ),
                (
                    "initial_moisture_pct",
                    models.FloatField(default=35, verbose_name="humedad inicial (%)"),
                ),
                (
                    "initial_nitrogen_ppm",
                    models.FloatField(default=70, verbose_name="N inicial (ppm)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "En ejecución"),
                            ("done", "Completada"),
                            ("failed", "Fallida"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="resultado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada el"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finalizada el"
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="soils.parcel",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulations",
                        to="crops.plant",
                    ),
                ),
                (
                    "soil_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulations",
                        to="soils.soilprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
