# Generated by Django 5.1.15 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("soils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="fecha y hora")),
                (
                    "temp_c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="temperatura (°C)"
                    ),
                ),
                (
                    "humidity_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="humedad relativa (%)"
                    ),
                ),
                (
                    "wind_ms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="viento (m/s)"
                    ),
                ),
                (
                    "rain_mm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="lluvia (mm)"
                    ),
                ),
                (
                    "solar_radiation_mj",
                    models.FloatField(
                        blank=True, null=True, verbose_name="radiación solar (MJ/m²)"
                    ),
                ),
                (
                    "et0_mm",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="evapotranspiración de referencia ET0 (mm)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("open_meteo", "Open-Meteo"),
                            ("openweather", "OpenWeather"),
                            ("estacion", "Estación propia"),
                        ],
                        default="open_meteo",
                        max_length=15,
                        verbose_name="fuente",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_records",
                        to="soils.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["parcel", "timestamp"],
                        name="weather_wea_parcel__cbf8db_idx",
                    )
                ],
            },
        ),
    ]
