# Generated by Django 5.1.15 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("soils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flown_at", models.DateTimeField(verbose_name="fecha del vuelo")),
                (
                    "ndvi_mean",
                    models.FloatField(blank=True, null=True, verbose_name="NDVI medio"),
                ),
                (
                    "ndre_mean",
                    models.FloatField(blank=True, null=True, verbose_name="NDRE medio"),
                ),
                (
                    "gndvi_mean",
                    models.FloatField(
                        blank=True, null=True, verbose_name="GNDVI medio"
                    ),
                ),
                (
                    "orthomosaic",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="drones/",
                        verbose_name="ortomosaico",
                    ),
                ),
                (
                    "zoning_map",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="drones/",
                        verbose_name="mapa de zonas de manejo",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drone_flights",
                        to="soils.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-flown_at"],
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=40, unique=True, verbose_name="código"),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("capacitivo", "Humedad capacitiva"),
                            ("tensiometro", "Tensiómetro"),
                            ("conductividad", "Conductividad eléctrica"),
                            ("clima", "Estación meteorológica"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "depth_cm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="profundidad (cm)"
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("lora", "LoRaWAN"),
                            ("mqtt", "MQTT"),
                            ("api", "API directa"),
                        ],
                        default="lora",
                        max_length=10,
                        verbose_name="protocolo",
                    ),
                ),
                (
                    "installed_at",
                    models.DateField(auto_now_add=True, verbose_name="instalado el"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="soils.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["parcel", "depth_cm"],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="fecha y hora")),
                (
                    "moisture_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="humedad (%)"
                    ),
                ),
                (
                    "temperature_c",
                    models.FloatField(
                        blank=True, null=True, verbose_name="temperatura (°C)"
                    ),
                ),
                (
                    "ec_ds_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="conductividad (dS/m)"
                    ),
                ),
                (
                    "battery_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="batería (%)"
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="monitoring.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "timestamp"],
                        name="monitoring__sensor__877d02_idx",
                    )
                ],
            },
        ),
    ]
