# Generated by Django 5.1.15 on 2026-09-08 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="installed_at",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="instalado el"
            ),
        ),
    ]
