# Generated by Django 5.1.15 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "species",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="especie (latín)"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("frutal", "Árbol frutal"),
                            ("hortaliza", "Hortaliza"),
                            ("cereal", "Cereal"),
                            ("oleaginosa", "Oleaginosa"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "cycle_days",
                    models.PositiveIntegerField(
                        verbose_name="duración del ciclo (días)"
                    ),
                ),
                (
                    "kc_initial",
                    models.FloatField(default=0.4, verbose_name="Kc inicial"),
                ),
                (
                    "kc_mid",
                    models.FloatField(default=1.1, verbose_name="Kc etapa media"),
                ),
                ("kc_end", models.FloatField(default=0.6, verbose_name="Kc final")),
                (
                    "root_depth_cm",
                    models.PositiveIntegerField(
                        default=40, verbose_name="profundidad radicular (cm)"
                    ),
                ),
                (
                    "growth_rate",
                    models.FloatField(
                        default=0.04, verbose_name="tasa de crecimiento (logística)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CropStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="etapa")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                ("day_start", models.PositiveIntegerField(verbose_name="día inicial")),
                ("day_end", models.PositiveIntegerField(verbose_name="día final")),
                (
                    "water_demand_mm_day",
                    models.FloatField(verbose_name="demanda hídrica (mm/día)"),
                ),
                (
                    "nitrogen_ppm",
                    models.FloatField(verbose_name="extracción de N (ppm)"),
                ),
                (
                    "phosphorus_ppm",
                    models.FloatField(default=0, verbose_name="extracción de P (ppm)"),
                ),
                (
                    "potassium_ppm",
                    models.FloatField(default=0, verbose_name="extracción de K (ppm)"),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crops.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["plant", "order"],
            },
        ),
    ]
