# Generated by Django 5.1.15 on 2026-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="latitud"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="longitud"),
                ),
                (
                    "area_ha",
                    models.FloatField(
                        blank=True, null=True, verbose_name="superficie (ha)"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SoilProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("franco", "Franco"),
                            ("arenoso", "Arenoso"),
                            ("arcilloso", "Arcilloso"),
                            ("fibra_coco", "Fibra de coco (sustrato)"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="tipo de suelo",
                    ),
                ),
                ("ph", models.FloatField(blank=True, null=True, verbose_name="pH")),
                (
                    "organic_matter_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="materia orgánica (%)"
                    ),
                ),
                (
                    "electrical_conductivity",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="conductividad eléctrica (dS/m)",
                    ),
                ),
                (
                    "sampled_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de muestreo"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_profiles",
                        to="soils.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["-sampled_at"],
            },
        ),
        migrations.CreateModel(
            name="SoilLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "depth_from_cm",
                    models.PositiveIntegerField(
                        verbose_name="profundidad inicial (cm)"
                    ),
                ),
                (
                    "depth_to_cm",
                    models.PositiveIntegerField(verbose_name="profundidad final (cm)"),
                ),
                (
                    "sand_pct",
                    models.FloatField(blank=True, null=True, verbose_name="arena (%)"),
                ),
                (
                    "silt_pct",
                    models.FloatField(blank=True, null=True, verbose_name="limo (%)"),
                ),
                (
                    "clay_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="arcilla (%)"
                    ),
                ),
                (
                    "field_capacity_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="capacidad de campo (%)"
                    ),
                ),
                (
                    "wilting_point_pct",
                    models.FloatField(
                        blank=True, null=True, verbose_name="punto de marchitez (%)"
                    ),
                ),
                (
                    "bulk_density",
                    models.FloatField(
                        blank=True, null=True, verbose_name="densidad aparente (g/cm³)"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="soils.soilprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["depth_from_cm"],
            },
        ),
    ]
